apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: florian-codebecq-autoscaler-deployment
  namespace: florian-codebecq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscaler-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
