apiVersion: apps/v1
kind: Deployment
metadata:
  name: florian-codebecq-database-deployment
  namespace: florian-codebecq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: florianc04/counter-database
