apiVersion: apps/v1
kind: Deployment
metadata:
  name: florian-codebecq-server-deployment
  namespace: florian-codebecq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: florianc04/counter-server
